name: 02 - Workflow Events
on: [workflow_dispatch, push]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the triggers
        run: echo "I have been triggered by a ${{ github.event_name }} event"
  
