name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false

env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'

jobs:
  echo-data:
    env:
      MY_JOB_VAR: 'job'
      MY_OVERWRITTEN_VAR: 'job'
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "Event name: ${{github.event_name}}"
          echo "Ref:${{github.ref_name}}"
          echo "SHA:${{github.sha}}" 
          echo "Actor:${{github.actor}}"
          echo "Workflow: ${{github.workflow}}"
          echo "Run ID: ${{github.run_id}}"
          echo "Run number: ${{github.run_number}}"
      - name: Display Variable info
        run: |
          echo "My Variable: ${{ vars.MY_VAR}}"
      
      - name: Print Env variables
        env:
          MY_OVERWRITTEN_VAR: 'step'
        run: |
          echo "My workflow Env variable: ${{ env.MY_WORKFLOW_VAR }}"
          echo "My workflow overwritten Env variable: ${{ env.MY_OVERWRITTEN_VAR }}"
          echo "My Job Env variable: ${{ env.MY_JOB_VAR }}"
          echo "My Job Overwritten Env variable: ${{ env.MY_OVERWRITTEN_VAR}}"

      - name: Print Env variables 2
        run: |
          echo "My workflow Env variable: ${{ env.MY_WORKFLOW_VAR }}"
          echo "My workflow overwritten Env variable: ${{ env.MY_OVERWRITTEN_VAR }}"
          echo "My Job Env variable: ${{ env.MY_JOB_VAR }}"
          echo "My Job Overwritten Env variable: ${{ env.MY_OVERWRITTEN_VAR}}"
          

  echo-data2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Env variables 2
        run: |
          echo "My workflow Env variable: $MY_WORKFLOW_VAR"
          echo "My workflow overwritten Env variable: $MY_OVERWRITTEN_VAR"
        