name: 15 - Working with Matrices
on:
  workflow_dispatch:
jobs:
  backwards-compatibility:
    name: Running on ${{ matrix.os }} with node-version ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true # Use false for jobs to not fail if one of the matrix job fails; it is true by default
      matrix: 
        node-version: [18.x, 20.x, 21.x]
        os:
          - ubuntu-latest
          - windows-latest
        include: # We can add something specific and do not want have that applicable to all the available ones in matrix section
          - os: ubuntu-latest
            node-version: '16.x'
          - os: ubuntu-latest
            node-version: '21.x'
            tag: experimental
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}

      - name: Fail if experimental
        if: matrix.tag == 'experimental'
        run: exit 0


      - name: Perform some tests
        run: |
          echo "Running tests on OS ${{ matrix.os}} and NodeJS ${{ matrix.node-version }}"
          sleep 10
      
      - name: Upload test results
        run: echo "Uploading test results"

  include-example:
    name: ${{ matrix.color}}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true # Use false for jobs to not fail if one of the matrix job fails; it is true by default
      matrix: 
        color: [red, green]
        shape: [circle, square] 
        size: [small, large]
        os:
          - ubuntu-latest
        include:  # include can be used to add additional jobs with the parameters that we pass in. It will not override the exisiting jobs if the paramters you passed is different
          - opacity: 50 # If you have a paramter like this only in include that gets used in all the jobs that get genereated, but the one with include will not have this
                        # https://github.com/Arjun0889/my-github-actions-course/actions/runs/13480919935/job/37665965401
          - color: red
            opacity: 75
            os: ubuntu-latest

    steps:
      - name: Dummy step
        run: |
          echo "${{ matrix.color}}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"