name: 18 - 2 - Reusable Workflows
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflows.yaml
    with: 
      target-directory: 'my-target-dir'
  print-outputs:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Print outputs
        run: |
          echo "Build status: ${{ needs.deploy.outputs.build-status }}"
          echo "URL: ${{ needs.deploy.outputs.url }}"